# Site Info
title:          "The Warlord's Gambit"
description:    "A hub for resources and session notes related to *The Warlord's Gambit*"

# Author Info
author_name:    "Aidan Gowland"

# Site Settings
# url should be the domain, baseurl should be the repository name
url:            "https://agowland.github.io"
baseurl:        "/thewarlordsgambit"
permalink:      /posts/:title
timezone:       America/Los_Angeles
mathjax:        true

# Site Build
highlighter:    rouge
markdown:       kramdown
kramdown:
  input:        GFM
sass:
  style:        :compressed

# Other Params
include:        [ "robots.txt" ]
exclude:        [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "Gemfile.lock" ]
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"

defaults:
  -
    scope:
      path:         ""
    values:
      # Change "null" to "default" so your theme actually applies to your markdown files
      layout:       "default"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"