# Site Info
title:              "The Warlord's Gambit"
description:        "A portal to resources and session notes for *The Warlord's Gambit*."

# Author Info
author_name:        "Aidan Gowland" # Your name here


# Site Settings
url:                 https://agowland.github.io # Change to your site
baseurl:        /thewarlordsgambit

remote_theme: just-the-docs/just-the-docs

permalink: pretty

search_enabled: true
aux_links: 
    "The Warlord's Gambit on GitHub":
      - "https://github.com/agowland/thewarlordsgambit"